import { ExportTheme } from '../types/theme';
import { ThemeId } from '../types/exportSettings';

export const THEME_REGISTRY: Record<ThemeId, ExportTheme> = {
  classique: {
    id: 'classique',
    label: 'Roman Classique',
    fonts: { heading: 'Times-Roman', body: 'Times-Roman', folio: 'Times-Roman' },
    colors: { text: '#1a1a1a', accent: '#8a5a34', ruleLine: '#d1c7bd' },
    chapterOpening: 'drop-cap',
    headerStyle: 'author-title-alternating',
    folioStyle: 'outer-corner',
    ornamentGlyph: '❦',
    titlePageLayout: 'centered',
  },
  fantasy: {
    id: 'fantasy',
    label: 'Fantasy & Imaginaire',
    fonts: { heading: 'Times-Bold', body: 'Times-Roman', folio: 'Times-Roman' },
    colors: { text: '#111827', accent: '#4c1d95', ruleLine: '#8b5cf6' },
    chapterOpening: 'ornament',
    headerStyle: 'author-title-alternating',
    folioStyle: 'centered',
    ornamentGlyph: '✦',
    titlePageLayout: 'framed',
  },
  sf: {
    id: 'sf',
    label: 'Science-Fiction',
    fonts: { heading: 'Helvetica-Bold', body: 'Helvetica', folio: 'Helvetica' },
    colors: { text: '#0f172a', accent: '#0284c7', ruleLine: '#38bdf8' },
    chapterOpening: 'centered-number',
    headerStyle: 'title-only',
    folioStyle: 'outer-corner',
    ornamentGlyph: '❖',
    titlePageLayout: 'left-aligned',
  },
  polar: {
    id: 'polar',
    label: 'Polar / Noir',
    fonts: { heading: 'Courier-Bold', body: 'Times-Roman', folio: 'Courier' },
    colors: { text: '#18181b', accent: '#dc2626', ruleLine: '#ef4444' },
    chapterOpening: 'plain',
    headerStyle: 'title-only',
    folioStyle: 'outer-corner',
    titlePageLayout: 'left-aligned',
  },
  thriller: {
    id: 'thriller',
    label: 'Thriller Psychologique',
    fonts: { heading: 'Helvetica-Bold', body: 'Helvetica', folio: 'Helvetica' },
    colors: { text: '#09090b', accent: '#b91c1c', ruleLine: '#71717a' },
    chapterOpening: 'centered-number',
    headerStyle: 'author-title-alternating',
    folioStyle: 'centered',
    titlePageLayout: 'centered',
  },
  essai: {
    id: 'essai',
    label: 'Essai / Réflexion',
    fonts: { heading: 'Times-Bold', body: 'Times-Roman', folio: 'Times-Roman' },
    colors: { text: '#1c1917', accent: '#9a3412', ruleLine: '#c2410c' },
    chapterOpening: 'plain',
    headerStyle: 'author-title-alternating',
    folioStyle: 'outer-corner',
    titlePageLayout: 'centered',
  },
  biographie: {
    id: 'biographie',
    label: 'Mémoires / Biographie',
    fonts: { heading: 'Times-Bold', body: 'Times-Roman', folio: 'Times-Roman' },
    colors: { text: '#27272a', accent: '#047857', ruleLine: '#10b981' },
    chapterOpening: 'drop-cap',
    headerStyle: 'author-title-alternating',
    folioStyle: 'outer-corner',
    ornamentGlyph: '❧',
    titlePageLayout: 'centered',
  },
  jeunesse: {
    id: 'jeunesse',
    label: 'Jeunesse / Aventure',
    fonts: { heading: 'Helvetica-Bold', body: 'Helvetica', folio: 'Helvetica' },
    colors: { text: '#1e293b', accent: '#ea580c', ruleLine: '#f97316' },
    chapterOpening: 'ornament',
    headerStyle: 'title-only',
    folioStyle: 'centered',
    ornamentGlyph: '★',
    titlePageLayout: 'centered',
  },
  minimaliste: {
    id: 'minimaliste',
    label: 'Minimaliste Épuré',
    fonts: { heading: 'Helvetica', body: 'Helvetica', folio: 'Helvetica' },
    colors: { text: '#262626', accent: '#525252', ruleLine: '#a3a3a3' },
    chapterOpening: 'plain',
    headerStyle: 'none',
    folioStyle: 'centered',
    titlePageLayout: 'left-aligned',
  },
  prestige: {
    id: 'prestige',
    label: 'Édition Prestige',
    fonts: { heading: 'Times-Bold', body: 'Times-Roman', folio: 'Times-Roman' },
    colors: { text: '#1a100c', accent: '#b45309', ruleLine: '#f59e0b' },
    chapterOpening: 'drop-cap',
    headerStyle: 'author-title-alternating',
    folioStyle: 'outer-corner',
    ornamentGlyph: '❦',
    titlePageLayout: 'framed',
  },
};

export function getTheme(id: ThemeId): ExportTheme {
  return THEME_REGISTRY[id] || THEME_REGISTRY.classique;
}
